version: "3.7"
services:
  app:
    build:
      # args:
      #   user: root
      #   uid: 1000
      context: ./project
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel_app
    working_dir: /var/www/
    command: ["sh", "-c", "sleep 30 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"]
    depends_on:
      - db
    tty: true
    ports:
      - 8000:8000
    # volumes:
      # - ./project:/var/www
      # - ~/.ssh:/home/root/.ssh
      # - ./cache:/home/root/.composer/cache
      # - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    # volumes:
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./mysql/my.cnf:/etc/my.cnf
    networks:
      - app-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx_server
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./project:/var/www
  #     - ./nginx:/etc/nginx/conf.d/
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge